### ISSUE TITLE
Why does this error keep appearing?

### ISSUE THREAD

**Issue by Yushe** [ctrlcctrlv/infinity#383]
I have installed the infinity script on my site but for some reason this error "Undefined index: mask_db_error" keeps appearing when I try to do anything on the site.

Please help!

**Comment by bui** [comment]
add `$config['mask_db_error'] = true;` to your instance-config.php

**Comment by Yushe** [comment]
Now it is saying this "Undefined index: mask_db_error"

**Comment by bui** [comment]
...that's the same error?

**Comment by Yushe** [comment]
Yes I know it is still appearing and I don't know why.

**Comment by Yushe** [comment]
I fixed that now this is coming up "Use of undefined constant BOARDVOLUNTEER - assumed 'BOARDVOLUNTEER'"

**Comment by ctrlcctrlv** [comment]
Seems to me like you didn't follow the instructions and you used install.php 

Do `git checkout inc/instance-config.php`

**Comment by Yushe** [comment]
But I don't know how to do a "git checkout" because I'm kinda new to github and the commands of it in general.

**Comment by AnonTheCuck** [comment]
git clone https://github.com/ctrlcctrlv/infinity.git

That's what you are looking for.

**Comment by Yushe** [comment]
Ok I installed an older version via fork that works better with my host.

I'm getting these two errors:

When creating a board with create.php: ```You failed the game```

When creating a board with mod.php: ```Column count doesn't match value count at row 1```

**Comment by Yushe** [comment]
Ok I got the updated version working but this message pops up when I try to create a thread: ```shell_exec() has been disabled for security reasons```

**Comment by bui** [comment]
are you using shared hosting? your provider has probably disabled it

**Comment by AnonTheCuck** [comment]
Check your php.ini for the disabled functions. If you don't have access to
it, you can be very dangerous and remove it (for educational purposes
only).

**Comment by Yushe** [comment]
I'm currently hosting with hostinger and I checked they don't let you edit php.ini but I'm thinking of upgrading to digitalocean.

**Comment by Yushe** [comment]
Ok I'm using digitalocean now and I installed it correctly but when I log in to mod.php this error appears

```Fatal error: Call to undefined function apc_fetch() in /var/www/html/inc/cache.php on line 45 Fatal error: Call to undefined function apc_fetch() in /var/www/html/inc/cache.php on line 45```

**Comment by bui** [comment]
apt-get install php5-apc
if that fails, apt-get install php-apc

**Comment by Yushe** [comment]
Ok I ran the rebuild thing and then created a board and I got this:

```Caught fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "ad_top.html" (looked into: /var/www/html/templates) in "index.html" at line 41.' in /var/www/html/inc/lib/Twig/Loader/Filesystem.php:202Stack trace:#0 /var/www/html/inc/lib/Twig/Loader/Filesystem.php(138): Twig_Loader_Filesystem->findTemplate('ad_top.html')#1 /var/www/html/inc/lib/Twig/Environment.php(273): Twig_Loader_Filesystem->getCacheKey('ad_top.html')#2 /var/www/html/inc/lib/Twig/Environment.php(320): Twig_Environment->getTemplateClass('ad_top.html', NULL)#3 /var/www/html/inc/lib/Twig/Environment.php(328) : eval()'d code(168): Twig_Environment->loadTemplate('ad_top.html')#4 /var/www/html/inc/lib/Twig/Template.php(266): __TwigTemplate_8bb56623cb9484a789b45f56c3cfdfe9fe2673e492fb276815cbfcf975d42afd->doDisplay(Array, Array)#5 /var/www/html/inc/lib/Twig/Template.php(240): Twig_Template->displayWithErrorHandling(Array, Array)#6 /var/www/html/inc/lib/Twig/Template.php(251): Twig_Template->display(Array)#7 /var/www/html/inc in /var/www/html/inc/lib/Twig/Loader/Filesystem.php on line 202```

**Comment by Yushe** [comment]
Ignore the above post I fixed it!
Everything is working perfectly apart from images don't appear unless I click on them, I went to the directory where the small images are kept and it says that the small ones are corrupted but the big ones are not. Why is this happening?

**Comment by ctrlcctrlv** [comment]
you need imagemagick

**Comment by Yushe** [comment]
When I change the settings of a board it says this: fopen(stylesheets/board/news.css): failed to open stream: Permission denied
But the settings do apply.
