### ISSUE TITLE
PHP Fatal Error in index.html line 1

### ISSUE THREAD

**Issue by xXxBobDolexXx** [ctrlcctrlv/infinity#519]
PHP Fatal error:  Uncaught exception 'Twig_Error_Syntax' with message
'Unclosed comment in "index.html" at line 1' in
/var/www/html/inc/lib/Twig/Lexer.php:307\nStack trace:\n#0
/var/www/html/inc/lib/Twig/Lexer.php(171): Twig_Lexer->lexComment()\n#1
/var/www/html/inc/lib/Twig/Lexer.php(107): Twig_Lexer->lexData()\n#2
/var/www/html/inc/lib/Twig/Environment.php(505):
Twig_Lexer->tokenize('<!doctype html>...', 'index.html')\n#3
/var/www/html/inc/lib/Twig/Environment.php(595):
Twig_Environment->tokenize('<!doctype html>...', 'index.html')\n#4
/var/www/html/inc/lib/Twig/Environment.php(332):
Twig_Environment->compileSource('<!doctype html>...', 'index.html')\n#5
/var/www/html/inc/lib/Twig/Environment.php(293):
Twig_Environment->loadTemplate('index.html')\n#6
/var/www/html/inc/template.php(70): Twig_Environment->render('index.html',
Array)\n#7 /var/www/html/inc/functions.php(1936): Element('index.html',
Array)\n#8 /var/www/html/inc/mod/pages.php(2415): buildIndex()\n#9 [internal
function]: mod_rebuild()\n#10 /var/www/html/mod.php(198): call_user in
/var/www/html/inc/lib/Twig/Lexer.php on line 307, referer:
http://rollerchan.xyz/mod.php?/rebuild

This happens when I try to rebuild, I'm not sure what to do to resolve this

**Comment by xXxBobDolexXx** [comment]
Issue has been resolved, I needed to obtain a copy of the .js file that was being requested which didn't seam to be in the templates for some reason
